"""creating tables

Revision ID: 8398dfe233a4
Revises: 
Create Date: 2025-12-13 00:59:17.432514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8398dfe233a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_MISSION', 'MAINTENANCE', name='dronestatus'), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('last_known_lat', sa.Float(), nullable=True),
    sa.Column('last_known_lng', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.create_table('surveyareas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon_coordinates', sa.JSON(), nullable=False),
    sa.Column('total_area_sq_m', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveyareas_id'), 'surveyareas', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('survey_area_id', sa.UUID(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('overlap_percentage', sa.Float(), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('data_collection_frequency', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'PAUSED', 'COMPLETED', 'ABORTED', name='missionstatus'), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['survey_area_id'], ['surveyareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_table('flightpaths',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.Enum('CROSSHATCH', 'PERIMETER', 'CUSTOM', name='pathpattern'), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_index(op.f('ix_flightpaths_id'), 'flightpaths', ['id'], unique=False)
    op.create_table('missionreports',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('total_flight_time', sa.Float(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('total_coverage', sa.Float(), nullable=True),
    sa.Column('battery_used', sa.Float(), nullable=True),
    sa.Column('summary_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_index(op.f('ix_missionreports_id'), 'missionreports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missionreports_id'), table_name='missionreports')
    op.drop_table('missionreports')
    op.drop_index(op.f('ix_flightpaths_id'), table_name='flightpaths')
    op.drop_table('flightpaths')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_surveyareas_id'), table_name='surveyareas')
    op.drop_table('surveyareas')
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.drop_table('drones')
    # ### end Alembic commands ###
